import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/userContext";
import { DeviceProvider } from "@/contexts/deviceContext";
import AuthProvider from "@/contexts/authContext";
import { ThemeCapartProvider } from "@/contexts/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by yours",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DeviceProvider>
          <AuthProvider>
            <UserProvider>
              <ThemeCapartProvider>{children}</ThemeCapartProvider>
            </UserProvider>
          </AuthProvider>
        </DeviceProvider>
      </body>
    </html>
  );
}
