import Header from "@/organisms/Header/Header";
import AdminTemplate from "@/templates/AdminTemplate/AdminTemplate";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by yours",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AdminTemplate sx={{ px: 1, my: 5 }}>{children}</AdminTemplate>;
}
